# Generated by Django 5.2.14 on 2026-05-26 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilityRawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("meter_number", models.CharField(blank=True, max_length=100)),
                ("meter_read_date", models.CharField(blank=True, max_length=50)),
                ("billing_start_date", models.CharField(blank=True, max_length=50)),
                ("billing_end_date", models.CharField(blank=True, max_length=50)),
                (
                    "consumption",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("consumption_unit", models.CharField(blank=True, max_length=20)),
                ("tariff_name", models.CharField(blank=True, max_length=200)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("facility_name", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_rows",
                        to="ingestion.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "row_index"],
            },
        ),
    ]
