# Generated by Django 5.2.14 on 2026-05-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_utilityrawrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="SapRawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("material_number", models.CharField(blank=True, max_length=100)),
                ("material_description", models.CharField(blank=True, max_length=500)),
                ("plant_code", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("posting_date", models.CharField(blank=True, max_length=50)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                ("material_group", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_rows",
                        to="ingestion.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "row_index"],
            },
        ),
    ]
