# Generated by Django 5.2.14 on 2026-05-26 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_saprawrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelRawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("car_rental", "Car Rental"),
                            ("rideshare", "Rideshare"),
                            ("train", "Train"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employee_name", models.CharField(blank=True, max_length=200)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("origin", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                ("departure_date", models.CharField(blank=True, max_length=50)),
                ("return_date", models.CharField(blank=True, max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hotel_nights", models.IntegerField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_rows",
                        to="ingestion.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "row_index"],
            },
        ),
    ]
