# Generated by Django 5.2.14 on 2026-05-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0004_travelrawrow"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("factor", models.DecimalField(decimal_places=6, max_digits=14)),
                ("factor_unit", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=50)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=20)),
                ("source_row_id", models.UUIDField(blank=True, null=True)),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("activity_type", models.CharField(blank=True, max_length=200)),
                (
                    "activity_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("activity_unit", models.CharField(blank=True, max_length=50)),
                ("emission_factor_used", models.CharField(blank=True, max_length=255)),
                ("co2e_amount", models.DecimalField(decimal_places=4, max_digits=16)),
                ("activity_date_start", models.DateField(blank=True, null=True)),
                ("activity_date_end", models.DateField(blank=True, null=True)),
                ("facility_or_plant", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("approved", "Approved"),
                            ("locked", "Locked"),
                            ("rejected", "Rejected"),
                        ],
                        default="imported",
                        max_length=20,
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("missing_data", "Missing Data"),
                            ("outlier", "Outlier"),
                            ("unit_ambiguity", "Unit Ambiguity"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("analyst_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emission_records",
                        to="ingestion.importbatch",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("approve", "Approve"),
                            ("flag", "Flag"),
                            ("reject", "Reject"),
                            ("lock", "Lock"),
                            ("edit", "Edit"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emission_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="emissions.emissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "status"], name="emissions_e_organiz_a7c7c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "scope"], name="emissions_e_organiz_cfc59b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "flag"], name="emissions_e_organiz_2e744a_idx"
            ),
        ),
    ]
